use_frameworks!

platform :ios, '9.0'

target 'LSJHImageCropController_Example' do
  pod 'LSJHImageCropController', :path => '../'

  target 'LSJHImageCropController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
